Attempt to make this all easier to build. Instructions shoudl be clear enough, but no doubt we have some people who can improve them. This should now build for most people and hopefully a few more folks can try it and find out where bugs are!
Where are all those people who said they'd test for us???

diff --git a/net_kit/source/server/Makefile b/net_kit/source/server/Makefile
--- a/net_kit/source/server/Makefile
+++ b/net_kit/source/server/Makefile
@@ -1,4 +1,5 @@
 SUBDIRS=net_server ipv4 udp ethernet arp icmp loop test 
+KERNELDIRS=net_server arp ethernet ipv4 loop udp
 
 # for profiling, uncomment these next 2 lines.
 #CFLAGS=-O0 -p -g -Wall -fPIC -DPIC
@@ -11,7 +12,6 @@ LDFLAGS=-nostdlib -L/boot/beos/system/lib -L/boot/develop/lib/x86 -lroot -lbe /b
 # Uncomment these to build a device driver!
 #CFLAGS=-nostart -no-fpic -D_KERNEL_MODE
 #LDFLAGS=-nostdlib /boot/develop/lib/x86/_KERNEL_
-
 
 INCLUDES=-I. -I./include
 
@@ -31,9 +31,43 @@ subdirs: $(OBJS)
 	done;
 	@if test -e _APP_; then rm _APP_; fi
 
+installkernel: clean
+	if ! test -d /boot/home/config/add-ons/kernel/network; then \
+		mkdir /boot/home/config/add-ons/kernel/network; \
+		mkdir /boot/home/config/add-ons/kernel/network/interface; \
+		mkdir /boot/home/config/add-ons/kernel/network/protocol; \
+		mkdir /boot/home/config/add-ons/kernel/network/misc; \
+	fi
+	for i in $(KERNELDIRS); do \
+		(cd $$i && $(MAKE) installkernel) || exit 1; \
+	done
+	@echo '***** WARNING *****'
+	@echo "Before trying to use the kernel implementation of the"
+	@echo "stack (just installed), you need to do the following:"
+	@echo "1. Go to the network preferences app and disable ALL"
+	@echo "   network cards listed there."
+	@echo "2. Restart the network."
+	@echo "3. Do make installdriver from this directory"
+	@echo "No restart should be required, but it may not be a bad idea :)"
+	@echo "When ready to try the new stack, run the test app, found in"
+	@echo 'the apps directory below this one.'
+	@echo 'NB NB NB'
+	@echo "To change back to using the old net stack, do this:"
+	@echo "1. Do make removedriver from this directory"
+	@echo "2. Restart the computer"
+	@echo "3. Go to the network preferences panel and enable the cards"
+	@echo "   you want and restart the network."
+	@echo 'While we know this is all a little like MicroSoft, please'
+	@echo "follow the instructions or kernel debugger land will be"
+	@echo "on your travel plans!"
+
+installdriver:
+	(cd ../driver && make install) || exit 1
+
+removedriver:
+	(cd ../driver && make clean) || exit 1
+
 clean:
-	@if test -e pools.o; then rm *.o; fi
-	@if test -e test_mbuf; then rm test_mbuf; fi
 	@if test -e net_srv; then rm net_srv; fi
 	@for i in $(SUBDIRS); do \
 		(cd $$i && $(MAKE) clean) || exit 1; \
